# note.py (schemas)
# Pydantic schemas define the shape of data at the API boundary.
# These are NOT database models — they are validation + serialization contracts.
#
# Three schemas:
#   NoteCreate   → what the frontend must send to create a note
#   NoteUpdate   → what the frontend can send to update a note
#   NoteResponse → what the API always sends back to the frontend

from pydantic import BaseModel, Field
# BaseModel → parent class for all Pydantic schemas
#             automatically validates types, required fields, and constraints
# Field     → lets you add metadata to a field: description, example, min_length etc.

from datetime import datetime
# datetime → Python's built-in type for date+time values
#            Pydantic uses this to validate and serialize timestamp fields

from typing import Optional
# Optional[X] is shorthand for Union[X, None]
# It means: this field can be type X or it can be absent/None


# ─── NoteCreate ───────────────────────────────────────────────────────────────
# Used when: POST /notes
# The frontend sends a JSON body that must match this schema exactly.
# If title or content is missing → Pydantic raises a 422 Validation Error automatically.
# You never manually check "is title present?" — Pydantic does it for you.
class NoteCreate(BaseModel):
    title: str = Field(
        ...,                          # ... means this field is REQUIRED (no default)
        min_length=1,                 # title cannot be an empty string
        max_length=255,               # matches the String(255) in our SQLAlchemy model
        description="Title of the note"
    )
    content: str = Field(
        ...,                          # required
        min_length=1,                 # content cannot be empty
        description="Body content of the note"
    )


# ─── NoteUpdate ───────────────────────────────────────────────────────────────
# Used when: PUT /notes/{id}
# ALL fields are Optional — the frontend can send just title, just content, or both.
# This is a "partial update" pattern: only provided fields get updated in the DB.
# If neither field is sent → the route will handle that gracefully in Phase 6.
class NoteUpdate(BaseModel):
    title: Optional[str] = Field(
        None,                         # None = not required, defaults to None if absent
        min_length=1,
        max_length=255,
        description="Updated title of the note"
    )
    content: Optional[str] = Field(
        None,
        min_length=1,
        description="Updated content of the note"
    )


# ─── NoteResponse ─────────────────────────────────────────────────────────────
# Used when: ALL responses — POST, GET, PUT return this shape
# This defines exactly what JSON the frontend receives.
# Notice: includes id, created_at, updated_at — fields the frontend didn't send,
# but needs to receive (to display timestamps, to identify which note to edit/delete).
class NoteResponse(BaseModel):
    id: int                           # auto-generated by PostgreSQL
    title: str
    content: str
    created_at: datetime              # set by PostgreSQL on insert
    updated_at: datetime              # set by PostgreSQL on insert and update

    # ── model_config ──────────────────────────────────────────────────────────
    # By default, Pydantic only works with plain dicts.
    # SQLAlchemy returns ORM objects (instances of Note class), not dicts.
    # from_attributes=True tells Pydantic:
    #   "read field values from object attributes, not just dict keys"
    # Without this: response = NoteResponse(note_object) → ValidationError
    # With this:    response = NoteResponse.model_validate(note_object) → works
    model_config = {"from_attributes": True}